config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'records#index'
  resources :records do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '○' }
  ]
  
  include ActiveHash::Associations
  has_many :records
end

app/models/cut.rb
class Cut < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '○' }
  ]
  
  include ActiveHash::Associations
  has_many :records
end

app/models/parm.rb
class Parm < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '○' }
  ]
  
  include ActiveHash::Associations
  has_many :records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, :day, :manager, :cut_id, :color_id, :parm_id, :treatment_id, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :cut
  belongs_to :color
  belongs_to :parm
  belongs_to :treatment

  def self.search(search)
    if search != ""
      Record.where('name LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end
end

app/models/treatment.rb
class Treatment < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '○' }
  ]
  
  include ActiveHash::Associations
  has_many :records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, only: [:edit, :show, :update, :destroy]
  def index
    @records = Record.order("day DESC")
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.create(record_params)
    if @record.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to action: :index
  end

  def search
    @record = Record.search(params[:keyword])
  end

  private

  def record_params
    params.require(:record).permit(:image, :name, :description, :cut_id, :color_id, :parm_id, :treatment_id, :day, :manager).merge(user_id: current_user.id)
  end
  
  def set_tweet
    @record = Record.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user.id != @record.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <%# <meta name="viewport" content="width=device-width, initial-scale=1.0" /> %>
    <title>karty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet"> %>
  </head>
  <body>
    <header class="bg-primary p-3 ">
      <div class="row">
        <div class="col ">
          <%= link_to "KARTY", root_path, class: "text-light text-decoration-none" %>
        </div>
        <div class="col text-end">
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-dark text-decoration-none" %>
            <%= link_to "カルテを入力", new_record_path, class: "text-dark text-decoration-none" %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "text-dark text-decoration-none" %>
            <%= link_to "新規登録", new_user_registration_path, class: "text-dark text-decoration-none"%>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="bg-secondary text-light text-center fixed-bottom">
      <p class="fs-6">Copyright © KARTY.com</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%# <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script> %>
    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with model: @record, local: true do |f|%>
  <div class="field">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, id:"customer_name" %>
  </div>
  <div class='input-day-wrap'>
    <%= raw sprintf(
                  f.date_select(
                    :day,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2000,
                    end_year: (Time.now.year ),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    <div class="field">
      <%= f.label :manager, "担当者" %><br />
      <%= f.text_field :manager, class: :form__text, id:"customer_manager" %>
    </div>
    <div class="field">
      <%= f.label :cut_id, "カット" %><br />
      <%= f.collection_select(:cut_id, Cut.all, :id, :name, {}, {class:"cut-select"}) %>
    </div>
    <div class="field">
      <%= f.label :color_id, "カラー" %><br />
      <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"color-select"}) %>
    </div>
    <div class="field">
      <%= f.label :parm_id, "パーマ" %><br />
      <%= f.collection_select(:parm_id, Parm.all, :id, :name, {}, {class:"parm-select"}) %>
    </div>
    <div class="field">
      <%= f.label :treatment_id, "トリートメント" %><br />
      <%= f.collection_select(:treatment_id, Treatment.all, :id, :name, {}, {class:"treatment-select"}) %>
    </div>
    <div class="field">
      <%= f.label :description, "備考" %><br />
      <%= f.text_area :description, class: :form__text, id:"customer_others" %>
    </div>
    <div class="field">
      <%= f.label :image, "画像" %><br />
      <%= f.file_field :image, id:"customer_image" %>
    </div>
    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  <% end %>

app/views/records/_record.html.erb
<% if user_signed_in? && current_user.id == record.user_id %>
<th scope="row"></th>
<td><%= link_to "#{record.name}様", record_path(record.id)%></td>
<td><%= record.manager %></td>
<td><%= record.day %></td>
</tr>
<% end %>

app/views/records/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">来店履歴編集</h2>
      <%= render partial: "form", locals: { record: @record } %>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<main class="main">
  <div class="inner">    
    <%= form_with(url: search_records_path, local: true, method: :get ) do |form| %>
      <%= form.text_field :keyword, placeholder: "お客様を検索する" %>
      <%= form.submit "検索" %>
    <% end %>
    <table class="table">
    <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">氏名</th>
      <th scope="col">担当者</th>
      <th scope="col">来店日</th>
    </tr>
  </thead>
      <thead>
        <%= render partial: 'record', collection: @records %>
      </thead>
    </table>
    
  </div>
</div>
</main>

app/views/records/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">施術記録</h2>
        <%= render partial: "form", locals: { record: @record } %>
    </div>
  </div>
</div>

app/views/records/search.html.erb
<%= form_with(url: search_records_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<table class="table">
<thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">氏名</th>
      <th scope="col">担当者</th>
      <th scope="col">来店日</th>
    </tr>
  </thead>
  <thead>
    <% @record.each do |record| %>
      <%= render partial: "record", locals: { record: record } %>
    <% end %>
  </thead>
</table>

app/views/records/show.html.erb
<div class="container ">
  <div class="col">
    <%= "#{@record.name}様" %>
  </div>
  <div class="col">
    <%= "担当 #{@record.manager}" %>
  </div>
  <div class="col">
    <%= "カット#{@record.cut.name}" %>
  </div>
  <div class="col">
    <%= "カラー#{@record.color.name}" %>
  </div>
  <div class="col">
    <%= "パーマ#{@record.parm.name}" %>
  </div>
  <div class="col">
    <%= "トリートメント#{@record.treatment.name}" %>
  </div>
  <div class="col">
    <%= "備考 #{@record.description}" %>
  </div>
  <%= link_to "編集する", edit_record_path %>
  <%= link_to "削除する", record_path, method: :delete %>
  <% if @record.image.attached? %>
    <div class="row">
      <div class="col-4 ">
        <%= image_tag @record.image, class: "img-fluid"%>
      </div>
    </div>
  <% end %>
</div>